Traceback (most recent call last):
  File "/Users/rubiarg/.virtualenvs/cpsc554x/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/rubiarg/.virtualenvs/cpsc554x/lib/python3.9/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/rubiarg/.virtualenvs/cpsc554x/lib/python3.9/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/rubiarg/.virtualenvs/cpsc554x/lib/python3.9/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/rubiarg/.virtualenvs/cpsc554x/lib/python3.9/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/Users/rubiarg/.virtualenvs/cpsc554x/lib/python3.9/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/rubiarg/.virtualenvs/cpsc554x/lib/python3.9/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#---------------------------------------
# fitting the order of the VAR
#--------------------------------------

# To select the right order of the VAR model, we iteratively fit increasing orders 
# of VAR model and pick the order that gives a model with least AIC.

model = VAR(df_differenced)
for i in [1,2,3,4,5,6,7,8,9]:
    result = model.fit(i)
    print('Lag Order =', i)
    print('AIC : ', result.aic)
    print('BIC : ', result.bic)
    print('FPE : ', result.fpe)
    print('HQIC: ', result.hqic, '\n')
    
# In the above output, the AIC drops to lowest at lag 4, then increases at 
# lag 5 and then continuously drops further. (more negative = 'smaller' AIC)

#---------------------------------
# alterntative: auto fit
#---------------------------------

x = model.select_order(maxlags=12)
x.summary()


#----------------------------------
# fit VAR(4)
#---------------------------------

model_fitted = model.fit(4)
model_fitted.summary()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m/var/folders/bl/2tw1vrc12mv_hqpbdf1j3wkw0000gn/T/ipykernel_16019/142197828.py[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m [0;31m# of VAR model and pick the order that gives a model with least AIC.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0;34m[0m[0m
[0;32m----> 8[0;31m [0mmodel[0m [0;34m=[0m [0mVAR[0m[0;34m([0m[0mdf_differenced[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      9[0m [0;32mfor[0m [0mi[0m [0;32min[0m [0;34m[[0m[0;36m1[0m[0;34m,[0m[0;36m2[0m[0;34m,[0m[0;36m3[0m[0;34m,[0m[0;36m4[0m[0;34m,[0m[0;36m5[0m[0;34m,[0m[0;36m6[0m[0;34m,[0m[0;36m7[0m[0;34m,[0m[0;36m8[0m[0;34m,[0m[0;36m9[0m[0;34m][0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     10[0m     [0mresult[0m [0;34m=[0m [0mmodel[0m[0;34m.[0m[0mfit[0m[0;34m([0m[0mi[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/.virtualenvs/cpsc554x/lib/python3.9/site-packages/statsmodels/tsa/vector_ar/var_model.py[0m in [0;36m__init__[0;34m(self, endog, exog, dates, freq, missing)[0m
[1;32m    551[0m         [0msuper[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0m__init__[0m[0;34m([0m[0mendog[0m[0;34m,[0m [0mexog[0m[0;34m,[0m [0mdates[0m[0;34m,[0m [0mfreq[0m[0;34m,[0m [0mmissing[0m[0;34m=[0m[0mmissing[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    552[0m         [0;32mif[0m [0mself[0m[0;34m.[0m[0mendog[0m[0;34m.[0m[0mndim[0m [0;34m==[0m [0;36m1[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 553[0;31m             [0;32mraise[0m [0mValueError[0m[0;34m([0m[0;34m"Only gave one variable to VAR"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    554[0m         [0mself[0m[0;34m.[0m[0mneqs[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mendog[0m[0;34m.[0m[0mshape[0m[0;34m[[0m[0;36m1[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m    555[0m         [0mself[0m[0;34m.[0m[0mn_totobs[0m [0;34m=[0m [0mlen[0m[0;34m([0m[0mendog[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mValueError[0m: Only gave one variable to VAR
ValueError: Only gave one variable to VAR

